INSERT INTO app_permiso ( "Nombre", "Tipo" )
VALUES( 'AdministrarProyectos', 'S' ),
      ( 'AdministrarUsuarios', 'S' ),
      ( 'AdministrarRoles', 'S' ),
      ( 'AdministrarTipoDeArtefacto', 'S' ),
      ( 'AsignarRolSistema', 'S' ),
      ( 'ConfigurarPermisos', 'S' ),
      ( 'Requerimientos', 'P'),
      ( 'Diseno', 'P'),
      ( 'Implementacion', 'P'),
      ( 'EditarProyecto', 'P' ),
      ( 'ConfigurarRelaciones', 'P' ),
      ( 'CalcularImpacto', 'P' ),
      ( 'GenerarLineaBase', 'P' ),
      ( 'AgregarMiembro', 'P' );