INSERT INTO app_permiso ( "Nombre", "Tipo" )
VALUES( 'CrearProyectos', 'S' ),
      ( 'EditarProyectos', 'S' ),
      ( 'EliminarProyectos', 'S' ),
      ( 'CrearUsuarios', 'S' ),
      ( 'EditarUsuarios', 'S' ),
      ( 'EliminarUsuarios', 'S' ),
      ( 'CrearRoles', 'S' ),
      ( 'EditarRoles', 'S' ),
      ( 'EliminarRoles', 'S' ),
      ( 'CrearTipoDeArtefacto', 'S' ),
      ( 'EditarTipoDeArtefacto', 'S' ),
      ( 'EliminarTipoDeArtefacto', 'S' ),
      ( 'AsignarRolSistema', 'S' ),
      ( 'ConfigurarPermisos', 'S' ),
      ( 'CrearArtefactoReq', 'P'),
      ( 'EditarArtefactoReq', 'P'),
      ( 'EliminarArtefactoReq', 'P'),
      ( 'CrearArtefactoDis', 'P'),
      ( 'EditarArtefactoDis', 'P'),
      ( 'EliminarArtefactoDis', 'P'),
      ( 'CrearArtefactoImp', 'P'),
      ( 'EditarArtefactoImp', 'P'),
      ( 'EliminarArtefactoImp', 'P'),
      ( 'EditarProyecto', 'P' ),
      ( 'ConfigurarRelaciones', 'P' ),
      ( 'CalcularImpacto', 'P' ),
      ( 'GenerarLineaBase', 'P' ),
      ( 'CrearMiembro', 'P' ),
      ( 'EditarMiembro', 'P' ),
      ( 'EliminarMiembro', 'P' ),
      ( 'CrearTipoArtefactoEspecifico', 'P' ),
      ( 'EditarTipoArtefactoEspecifico', 'P' ),
      ( 'EliminarTipoArtefactoEspecifico', 'P' );